from singer_sdk import typing as th

schema = th.PropertiesList(
    th.Property("dateTime", th.StringType),
    th.Property("dataSourceName", th.StringType),
    th.Property("projectName", th.StringType),
    th.Property("recordType", th.StringType),
    th.Property("blobId", th.StringType),
    th.Property("userId", th.StringType),
    th.Property("profileId", th.IntegerType),
    th.Property("purposeIds", th.ArrayType(th.StringType)),
    th.Property("success", th.BooleanType),
    th.Property("failureReason", th.StringType),
    th.Property("id", th.StringType),
    th.Property("fingerprintVersionName", th.StringType),
    th.Property("email", th.StringType),
).to_dict()

AUDIT_RECORD_TYPES = [
    'auditQuery',
    'blobVisibility',
    'blobFetch',
    'blobIndex',
    'blobDelete',
    'blobUpdateFeatures',
    'blobUpdateTags',
    'sqlAccess',
    'spark',
    'sqlCreateUser',
    'sqlDeleteUser',
    'sqlResetPassword',
    'featureList',
    'sqlQuery',
    'catalogUpdate',
    'dataSourceCreate',
    'dataSourceDelete',
    'dataSourceExpired',
    'dataSourceSave',
    'dataSourceGet',
    'dataSourceListMine',
    'dataSourceSubscription',
    'dataSourceTestQuery',
    'dbtApiKeyUpdate',
    'dbtDelete',
    'dictionaryCreate',
    'dictionaryDelete',
    'dictionaryUpdate',
    'nativeQuery',
    'projectCreate',
    'projectPurposeApprove',
    'projectPurposeDeny',
    'projectUpdate',
    'projectDelete',
    'addToProject',
    'removeFromProject',
    'projectSubscription',
    'acknowledgePurposes',
    'accessUser',
    'accessGroup',
    'apiKey',
    'tagAdded',
    'tagCreated',
    'tagDeleted',
    'tagUpdated',
    'tagRemoved',
    'sddClassifierCreated',
    'sddClassifierUpdated',
    'sddClassifierDeleted',
    'sddDatasourceTagUpdate',
    'sddTemplateCreated',
    'sddTemplateUpdated',
    'sddTemplateDeleted',
    'sddTemplateApplied',
    'authenticate',
    'checkPendingRequest',
    'policyExemption',
    'governanceUpdate',
    'purposeCreate',
    'purposeUpdate',
    'purposeDelete',
    'licenseCreate',
    'licenseDelete',
    'policyHandlerCreate',
    'policyHandlerUpdate',
    'policyAdjustmentCreate',
    'policyAdjustmentDelete',
    'policyAdjustmentExpired',
    'policyExport',
    'policyImport',
    'globalPolicyCertify',
    'policyCertificationExpired',
    'globalPolicyCreate',
    'globalPolicyUpdate',
    'globalPolicyDelete',
    'globalPolicyConflictResolved',
    'globalPolicyDisabled',
    'globalPolicyApplied',
    'globalPolicyRemoved',
    'externalUserIdChanged',
    'externalQuery',
    'fingerprintVersionCreate',
    'fingerprintVersionUpdate',
    'fingerprintVersionDelete',
    'unmaskRequest',
    'queryDebugRequest',
    'taskValidate',
    'taskDelete',
    'handleTask',
    's3pBlobFetch',
    'switchCurrentProject',
    'webhookCreate',
    'webhookDelete',
    'configurationUpdate',
    'driverUpload',
    'workSpace',
    'prestoQuery'
]
